apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-bloody-jenkins
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: my-bloody-jenkins
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: my-bloody-jenkins
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
